export const LANGUAGES = [
    "English",
    "Spanish",
    "French",
    "German",
    "Portuguese",
    "Italian",
    "Dutch",
    "Russian",
    "Arabic",
    "Chinese",
];
export const PROPERTYTYPE = [
    "-- Select --",
    "Detached",
    "Semi-detached",
    "Condo",
    "Apartment",
    "Flat",
    "Pad",
    "Land",
    "Vacant Lot",
    "Lot",
    "Parking Space",
    "Garage",
    "Barn",
    "Workshop",
    "Autoshop",
    "Shed",
];
export const STATUS = [
    "-- Select --",
    "For Sale",
    "Coming Soon",
    "Rental",
    "Lease",
    "Airbnb",
];
export const PURPOSE = [
    "-- Select --",
    "MLS write up/client remarks",
    "Blog post",
    "Magazine article",
    "Sales brochure",
];
